# Site settings
title: Sample Website
email: your-email@domain.com
description: This is a description of the website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cjorasch
github_username:  cjorasch

# Build settings
markdown: kramdown
